#config_version=5
##! mode: lanechange

mode:
  start_events: start_mode_lanechange
  stop_events: stop_mode_lanechange, ball_will_end



shot_groups:
  lanechange_group:
    shots: shot_laneleft_outer, shot_laneleft_inner, shot_laneright_inner, shot_laneright_outer
    reset_events: lanechange_group_hit_complete
    rotate_left_events: s_flipper_left_active
    rotate_right_events: s_flipper_right_active

sound_player:
  shot_laneleft_outer_hit:
    canopening:
      action: play   
  shot_laneleft_inner_hit:
    canopening:
      action: play  
  shot_laneright_inner_hit:
    canopening:
      action: play  
  shot_laneright_outer_hit:
    canopening:
      action: play  

variable_player:
  lanechange_group_hit_complete:
    score: 100000
    bonus_multiplier: 1



