#config_version=5
##! mode: high_score

mode:
  priority: 500
  start_events: game_ending, start_high_score
  use_wait_queue: true

high_score:
  _overwrite: true
  enter_initials_timeout: 60
  award_slide_display_time: 4s

  # define your high score categories and the awards
  categories: !!omap
    - score:
        - GRAND CHAMPION
        - HIGH SCORE 1
        - HIGH SCORE 2
        - HIGH SCORE 3
        - HIGH SCORE 4

  # set the defaults
  defaults:
    score:
      - OHM: 1000000
      - ALG: 900000
      - MPF: 800000
      - LRG: 700000
      - MRG: 600000

# optional: change the slides (you can omit all the following)
slide_player:
  _overwrite: true
  high_score_enter_initials: high_score_enter_initials
  high_score_award_display: high_score_award_display

slides:
  _overwrite: true
  high_score_enter_initials:
    - type: text
      font_size: 100
      font_name: druillet
      text: PLAYER (player_num)
      color: white
      anchor_x: middle
      anchor_y: top
      x: middle
      y: top - 25
    - type: text
      font_size: 100
      font_name: druillet
      text: (award)
      color: red
      anchor_y: top
      x: middle
      y: top - 250
    - type: text_input
      initial_char: A
      dynamic_x: false
      key: high_score
      font_size: 100
      font_name: druillet
      max_chars: 3
      anchor_y: top
      x: middle
      y: top - 650
      shift_left_event: s_flipper_left_active
      shift_right_event: s_flipper_right_active
      select_event: s_start_active
      color: red
    - type: text
      text: '<       >'
      font_size: 100
      font_name: druillet
      anchor_y: top
      x: middle
      y: top - 650
      color: red
    - type: text
      text: ''
      key: high_score
      font_size: 100
      font_name: druillet
      anchor_y: top
      x: middle
      y: top - 475
      color: green
      animations:
        show_slide:
          - property: opacity
            value: 1
            duration: 0.5s
            easing: in_out_quint
          - property: opacity
            value: 0
            duration: 0.5s
            repeat: true
            easing: in_out_quint
  high_score_award_display:
    - type: text
      text: (award)
      font_size: 125
      font_name: druillet
      anchor_x: middle
      anchor_y: top
      x: middle
      y: top - 15
      color: blue
    - type: text
      text: (player_name)
      font_size: 100
      font_name: druillet
      anchor_y: middle
      anchor_x: middle
      x: middle
      y: middle
      color: red
      animations:
        show_slide:
          - property: opacity
            value: 1
            duration: 0.05s
          - property: opacity
            value: 0
            duration: 0.05s
            repeat: true
    - type: text
      text: (value)
      anchor_x: middle
      anchor_y: bottom
      x: middle
      y: 15
      color: white
      font_size: 100
      font_name: druillet
      number_grouping: true
      min_digits: 1