#config_version=5
##! mode: spellbeer

mode:
  start_events: start_mode_spellbeer
  stop_events: stop_mode_spellbeer, ball_will_end



shot_groups:
  spellbeer_group:
    shots: shot_laneleft_outer, shot_laneleft_inner, shot_laneright_inner, shot_laneright_outer
    reset_events: spellbeer_group_hit_complete
    rotate_left_events: s_flipper_left_active
    rotate_right_events: s_flipper_right_active

sound_player:
  shot_laneleft_outer_hit:
    canopening:
      action: play   
  shot_laneleft_inner_hit:
    canopening:
      action: play  
  shot_laneright_inner_hit:
    canopening:
      action: play  
  shot_laneright_outer_hit:
    canopening:
      action: play

variable_player:
  spellbeer_group_hit_complete{mode.dasboot.active == False}:
    score: current_player.pts_spell_beer
    bonus_multiplier: 1



