#config_version=5
##! mode: mball_lock3

mode:
  restart_on_next_ball: true
  start_events: multiball_lock_pt_lock2_full
  stop_events: multiball_pt_multiball_started

multiball_locks:
  pt_lock3:
    lock_devices: bd_kicker_rimrules
    balls_to_lock: 1
    disable_events: mode_multiball_started
    reset_count_for_current_player_events: multiball_pt_multiball_started
    
