#config_version=5
##! mode: dasboot

#TODO Finish Wizard Mode

mode:
  start_events: start_mode_dasboot
  stop_events: stop_mode_dasboot, stop_missions   # NOT a timed round
  events_when_started: mode_type_mission_started
  events_when_stopped: mode_type_mission_stopped
  priority: 300


