#config_version=5
##! mode: bonusv2

mode:
  start_events: start_mode_bonus
  stop_events: stop_mode_bonus
  priority: 300

variable_player:
  # when bonus mode starts, compute all subtotal bonuses and total bonus
  mode_bonusv2_started:
    bonus_sub_quarters:
      action: set
      int: current_player.bonus_numquarters * 1500
    bonus_sub_hjs:
      action: set
      int: current_player.bonus_numhjs * 1200
    bonus_sub_bjs:
      action: set
      int: current_player.bonus_numbjs * 1000
    bonus_sub_zjs:
      action: set
      int: current_player.bonus_numzjs * 1500
    bonus_sub_strikeouts:
      action: set
      int: current_player.bonus_numstrikeouts * 2000
    bonus_sub_ramps:
      action: set
      int: current_player.bonus_numramps * 800
    bonus_total:
      action: set
      # below calculates a total based on total multiplier (bonus_numchance) times the multiplicative sum of the other bonuses based on above subtotal calculations
      int: current_player.bonus_numchance * ((current_player.bonus_numquarters * 1500) + (current_player.bonus_numhjs * 1200) + (current_player.bonus_numbjs * 1000) + (current_player.bonus_numzjs * 1500) + (current_player.bonus_numstrikeouts * 2000) + (current_player.bonus_numramps * 800))

  # when bonus mode is about to stop, update our total score and reset all bonus counters
  mode_bonusv2_will_stop:
    score:    # update player score
      action: set
      int: current_player.score + current_player.bonus_total
    # clear all counters associated with bonuses
    bonus_numquarters:
      action: set
      int: 0
    bonus_numhjs:
      action: set
      int: 0
    bonus_numbjs:
      action: set
      int: 0
    bonus_numzjs:
      action: set
      int: 0
    bonus_numstrikeouts:
      action: set
      int: 0
    bonus_numramps:
      action: set
      int: 0
    bonus_numchance:
      action: set
      int: 1

sound_player:
  slide_slide_bonus_quarters_active:
    prosit:
      loops: 0
  slide_slide_bonus_hjs_active:
    prosit:
      loops: 0
  slide_slide_bonus_bjs_active:
    prosit:
      loops: 0
  slide_slide_bonus_zjs_active:
    prosit:
      loops: 0
  slide_slide_bonus_strikeouts_active:
    prosit:
      loops: 0
  slide_slide_bonus_ramps_active:
    prosit:
      loops: 0
  slide_slide_bonus_chance_active:
    prosit:
      loops: 0
  slide_slide_bonus_total_active{current_player.bonus_total < 800}:
    frustrating:
      action: play
      events_when_stopped: slide_total_audio_complete
  slide_slide_bonus_total_active{current_player.bonus_total >= 800}:
    letsgetbombed:
      action: play
      events_when_stopped: slide_total_audio_complete
    
shows:
  # one of the below shows is chosen at random when bonus mode starts
  show_cantdrinkabeer:
    - time: 0
      slides: video_cantdrinkabeer_slide
    - time: '+2.55'
      events: drain_audio_complete
  show_firstbeer:
    - time: 0
      slides: video_firstbeer_slide
    - time: '+3.5'
      events: drain_audio_complete
  show_nipple:
    - time: 0
      slides: video_nipple_slide
    - time: '+5.25'
      events: drain_audio_complete

# one of these is chosen at random by random_event_player below
show_player:
  drain_play_cantdrinkabeer:
    show_cantdrinkabeer:
      loops: 0
  drain_play_firstbeer:
    show_firstbeer:
      loops: 0
  drain_play_nipple:
    show_nipple:
      loops: 0
      
# chooses a random clip to show when bonus mode is started
random_event_player:
  mode_bonusv2_started:
    events:
      - drain_play_cantdrinkabeer
      - drain_play_firstbeer
      - drain_play_nipple

slide_player:
  # first slide could be 1 of 6 bonuses
  drain_audio_complete{current_player.bonus_numquarters > 0}: slide_bonus_quarters
  drain_audio_complete{current_player.bonus_numquarters==0 and current_player.bonus_numhjs > 0}: slide_bonus_hjs
  drain_audio_complete{current_player.bonus_numquarters==0 and current_player.bonus_numhjs==0 and current_player.bonus_numbjs > 0}: slide_bonus_bjs
  drain_audio_complete{current_player.bonus_numquarters==0 and current_player.bonus_numhjs==0 and current_player.bonus_numbjs==0 and current_player.bonus_numzjs > 0}: slide_bonus_zjs
  drain_audio_complete{current_player.bonus_numquarters==0 and current_player.bonus_numhjs==0 and current_player.bonus_numbjs==0 and current_player.bonus_numzjs==0 and current_player.bonus_numstrikeouts > 0}: slide_bonus_strikeouts
  drain_audio_complete{current_player.bonus_numquarters==0 and current_player.bonus_numhjs==0 and current_player.bonus_numbjs==0 and current_player.bonus_numzjs==0 and current_player.bonus_numstrikeouts==0 and current_player.bonus_numramps > 0}: slide_bonus_ramps
  drain_audio_complete{current_player.bonus_numquarters==0 and current_player.bonus_numhjs==0 and current_player.bonus_numbjs==0 and current_player.bonus_numzjs==0 and current_player.bonus_numstrikeouts==0 and current_player.bonus_numramps==0}: slide_bonus_total
  
  slide_slide_bonus_quarters_removed{current_player.bonus_numhjs > 0}: slide_bonus_hjs
  slide_slide_bonus_quarters_removed{current_player.bonus_numhjs==0 and current_player.bonus_numbjs > 0}: slide_bonus_bjs
  slide_slide_bonus_quarters_removed{current_player.bonus_numhjs==0 and current_player.bonus_numbjs==0 and current_player.bonus_numzjs > 0}: slide_bonus_zjs
  slide_slide_bonus_quarters_removed{current_player.bonus_numhjs==0 and current_player.bonus_numbjs==0 and current_player.bonus_numzjs==0 and current_player.bonus_numstrikeouts > 0}: slide_bonus_strikeouts
  slide_slide_bonus_quarters_removed{current_player.bonus_numhjs==0 and current_player.bonus_numbjs==0 and current_player.bonus_numzjs==0 and current_player.bonus_numstrikeouts==0 and current_player.bonus_numramps > 0}: slide_bonus_ramps
  slide_slide_bonus_quarters_removed{current_player.bonus_numhjs==0 and current_player.bonus_numbjs==0 and current_player.bonus_numzjs==0 and current_player.bonus_numstrikeouts==0 and current_player.bonus_numramps==0}: slide_bonus_chance

  slide_slide_bonus_hjs_removed{current_player.bonus_numbjs > 0}: slide_bonus_bjs
  slide_slide_bonus_hjs_removed{current_player.bonus_numbjs==0 and current_player.bonus_numzjs > 0}: slide_bonus_zjs
  slide_slide_bonus_hjs_removed{current_player.bonus_numbjs==0 and current_player.bonus_numzjs==0 and current_player.bonus_numstrikeouts > 0}: slide_bonus_strikeouts
  slide_slide_bonus_hjs_removed{current_player.bonus_numbjs==0 and current_player.bonus_numzjs==0 and current_player.bonus_numstrikeouts==0 and current_player.bonus_numramps > 0}: slide_bonus_ramps
  slide_slide_bonus_hjs_removed{current_player.bonus_numbjs==0 and current_player.bonus_numzjs==0 and current_player.bonus_numstrikeouts==0 and current_player.bonus_numramps==0}: slide_bonus_chance

  slide_slide_bonus_bjs_removed{current_player.bonus_numzjs > 0}: slide_bonus_zjs
  slide_slide_bonus_bjs_removed{current_player.bonus_numzjs==0 and current_player.bonus_numstrikeouts > 0}: slide_bonus_strikeouts
  slide_slide_bonus_bjs_removed{current_player.bonus_numzjs==0 and current_player.bonus_numstrikeouts==0 and current_player.bonus_numramps > 0}: slide_bonus_ramps
  slide_slide_bonus_bjs_removed{current_player.bonus_numzjs==0 and current_player.bonus_numstrikeouts==0 and current_player.bonus_numramps==0}: slide_bonus_chance

  slide_slide_bonus_zjs_removed{current_player.bonus_numstrikeouts > 0}: slide_bonus_strikeouts
  slide_slide_bonus_zjs_removed{current_player.bonus_numstrikeouts==0 and current_player.bonus_numramps > 0}: slide_bonus_ramps
  slide_slide_bonus_zjs_removed{current_player.bonus_numstrikeouts==0 and current_player.bonus_numramps==0}: slide_bonus_chance

  slide_slide_bonus_strikeouts_removed{current_player.bonus_numramps > 0}: slide_bonus_ramps
  slide_slide_bonus_strikeouts_removed{current_player.bonus_numramps==0}: slide_bonus_chance

  slide_slide_bonus_ramps_removed: slide_bonus_chance

  slide_slide_bonus_chance_removed: slide_bonus_total

  slide_total_audio_complete:
    slide_bonus_total:
      action: remove

event_player:
  slide_slide_bonus_total_removed: stop_mode_bonus

# These slides are called from our bonus show above. They get data from current player variables data that is set when this bonus mode starts
slides:
  slide_bonus_quarters:
    widgets:
      - type: text
        text: "Quarters Bonus: (player|bonus_numquarters) x 1,500"
        font_size: 100
        font_name: druillet
        color: 008ce5ff
        anchor_y: top
        anchor_x: middle
        x: middle
        y: top - 100
      - type: text
        text: (player|bonus_sub_quarters)
        number_grouping: true
        min_digits: 1
        font_size: 10
        font_name: druillet
        color: 008ce5ff
        anchor_y: top
        anchor_x: middle
        x: middle
        y: top - 300
        animations:
          show_slide:
            - property: font_size
              value: 150
              duration: .25s
      - type: image
        image: background
    expire: 1s
  slide_bonus_hjs:
    widgets:
      - type: text
        text: "HJ Bonus: (player|bonus_numhjs) x 1,200"
        font_size: 100
        font_name: druillet
        color: 008ce5ff
        anchor_y: top
        anchor_x: middle
        x: middle
        y: top - 100
      - type: text
        text: (player|bonus_sub_hjs)
        number_grouping: true
        min_digits: 1
        font_size: 10
        font_name: druillet
        color: 008ce5ff
        anchor_y: top
        anchor_x: middle
        x: middle
        y: top - 300
        animations:
          show_slide:
            - property: font_size
              value: 150
              duration: .25s
      - type: image
        image: background
    expire: 1s
  slide_bonus_bjs:
    widgets:
      - type: text
        text: "BJ Bonus: (player|bonus_numbjs) x 1,000"
        font_size: 100
        font_name: druillet
        color: 008ce5ff
        anchor_y: top
        anchor_x: middle
        x: middle
        y: top - 100
      - type: text
        text: (player|bonus_sub_bjs)
        number_grouping: true
        min_digits: 1
        font_size: 10
        font_name: druillet
        color: 008ce5ff
        anchor_y: top
        anchor_x: middle
        x: middle
        y: top - 300
        animations:
          show_slide:
            - property: font_size
              value: 150
              duration: .25s
      - type: image
        image: background
    expire: 1s
  slide_bonus_zjs:
    widgets:
      - type: text
        text: "ZJ Bonus: (player|bonus_numzjs) x 1,500"
        font_size: 100
        font_name: druillet
        color: 008ce5ff
        anchor_y: top
        anchor_x: middle
        x: middle
        y: top - 100
      - type: text
        text: (player|bonus_sub_zjs)
        number_grouping: true
        min_digits: 1
        font_size: 10
        font_name: druillet
        color: 008ce5ff
        anchor_y: top
        anchor_x: middle
        x: middle
        y: top - 300
        animations:
          show_slide:
            - property: font_size
              value: 150
              duration: .25s
      - type: image
        image: background
    expire: 1s
  slide_bonus_strikeouts:
    widgets:
      - type: text
        text: "Strikeout Bonus: (player|bonus_numstrikeouts) x 2,000"
        font_size: 100
        font_name: druillet
        color: 008ce5ff
        anchor_y: top
        anchor_x: middle
        x: middle
        y: top - 100
      - type: text
        text: (player|bonus_sub_strikeouts)
        number_grouping: true
        min_digits: 1
        font_size: 10
        font_name: druillet
        color: 008ce5ff
        anchor_y: top
        anchor_x: middle
        x: middle
        y: top - 300
        animations:
          show_slide:
            - property: font_size
              value: 150
              duration: .25s
      - type: image
        image: background 
    expire: 1s 
  slide_bonus_ramps:
    widgets:
      - type: text
        text: "Ramp Bonus: (player|bonus_numramps) x 800"
        font_size: 100
        font_name: druillet
        color: 008ce5ff
        anchor_y: top
        anchor_x: middle
        x: middle
        y: top - 100
      - type: text
        text: (player|bonus_sub_ramps)
        number_grouping: true
        min_digits: 1
        font_size: 10
        font_name: druillet
        color: 008ce5ff
        anchor_y: top
        anchor_x: middle
        x: middle
        y: top - 300
        animations:
          show_slide:
            - property: font_size
              value: 150
              duration: .25s
      - type: image
        image: background
    expire: 1s
  slide_bonus_chance:
    widgets:
      - type: text
        text: "Chance Multiplier"
        font_size: 100
        font_name: druillet
        color: 008ce5ff
        anchor_y: top
        anchor_x: middle
        x: middle
        y: top - 100
      - type: text
        text: (player|bonus_numchance)X
        number_grouping: true
        min_digits: 1
        font_size: 10
        font_name: druillet
        color: 008ce5ff
        anchor_y: top
        anchor_x: middle
        x: middle
        y: top - 300
        animations:
          show_slide:
            - property: font_size
              value: 150
              duration: .25s
      - type: image
        image: background
    expire: 1.5s
  slide_bonus_total:
    widgets:
      - type: text
        text: "Total Bonus"
        font_size: 100
        font_name: druillet
        color: 008ce5ff
        anchor_y: top
        anchor_x: middle
        x: middle
        y: top - 100
      - type: text
        text: (player|bonus_total)
        number_grouping: true
        min_digits: 1
        font_size: 10
        font_name: druillet
        color: 008ce5ff
        anchor_y: top
        anchor_x: middle
        x: middle
        y: top - 300
        animations:
          show_slide:
            - property: font_size
              value: 175
              duration: .25s
      - type: image
        image: background

