#config_version=5

coils:
  # 48V Coil Driver PCB: A0
  # Bank A (A0-B0)
  c_flipper_right:
    number: A0-B0-0 # PD-16 Address 0, Bank A, Bit 1 for right flipper
    default_pulse_ms: 25
    default_hold_power: .125
  c_slingshot_right:
    number: A0-B0-1
    default_pulse_ms: 20
  c_kicker_mode:
    number: A0-B0-2
    default_pulse_ms: 35
  # A0-B0-3 and A0-B0-4 are unreliable now - probs with pong cup coils. May have burned out the outputs? Using A0-B1-5/6 now  
  c_popbumper_lower:
    number: A0-B0-5 # verified
    default_pulse_ms: 35
  c_popbumper_upper_left:
    number: A0-B0-6
    default_pulse_ms: 35
  c_popbumper_upper_right:
    number: A0-B0-7
    default_pulse_ms: 35
  # Bank B (A0-B1)
  c_flipper_left:
    number: A0-B1-0 # PD-16 Address 0, Bank A, Bit 0 for left flipper
    default_pulse_ms: 25
    default_hold_power: .125
  c_slingshot_left:
    number: A0-B1-1
    default_pulse_ms: 20
  c_slingshot_quarters:
    number: A0-B1-2
    default_pulse_ms: 35  
  c_strike_out:
    number: A0-B1-3
    default_pulse_ms: 35
  # A0-B1-4 unreliable. RimRules coil stopped firing...moved to A0-B1-7. Works again...
  c_pongcup1:
    number: A0-B1-5
    default_pulse_ms: 500
    default_hold_power: .5
    pulse_events: release_cup1    # adding this event removes the default pulse_event, which collecting_balls was using to fire the release coils too early.
  c_pongcup2:
    number: A0-B1-6
    default_pulse_ms: 500
    default_hold_power: .5
    pulse_events: release_cup2
  c_kicker_rimrules:
    number: A0-B1-7
    default_pulse_ms: 15

  # PD-LED is A1

  # 12V Coil Driver PCB: A2
  l_popbumper_lower:
    number: A2-B0-0
    default_pulse_ms: 50
    pulse_events: pop_light_lower
  l_popbumper_right:
    number: A2-B0-1
    default_pulse_ms: 50
    pulse_events: pop_light_right
  l_popbumper_left:
    number: A2-B0-2
    default_pulse_ms: 50
    pulse_events: pop_light_left
  c_trough_eject:
    number: A2-B0-3 # PD-16 Address 0, Bank B, Bit 1 will be drive pin for trough eject solenoid
    default_pulse_ms: 40
    default_hold_power: .5
  c_drain_eject:
    number: A2-B0-4 # PD-16 Address 0, Bank B, Bit 0 will be drive pin for drain-to-trough solenoid
    default_pulse_ms: 40
    default_hold_power: .5
  
autofire_coils:
  slingshot_left:
    coil: c_slingshot_left
    switch: s_slingshot_left
  slingshot_right:
    coil: c_slingshot_right
    switch: s_slingshot_right
  popbumper_lower:
    coil: c_popbumper_lower
    switch: s_popbumper_lower
  popbumper_upper_right:
    coil: c_popbumper_upper_right
    switch: s_popbumper_upper_right
  popbumper_upper_left:
    coil: c_popbumper_upper_left
    switch: s_popbumper_upper_left
  slingshot_quarters:
    coil: c_slingshot_quarters
    switch: s_slingshot_quarters

