#config_version=5

sounds:
  introrepeat:
    file: introrepeat1.wav
    track: music
    volume: 1.0
  intro:
    file: intro1.wav
    volume: 1.0
  music_bubbles:
    file: soundtrack-bubbles.wav
    volume: 1.0
  music_drinkonme:
    file: soundtrack-drinkonme.wav
    volume: 1.0
  music_hardasarock:
    file: soundtrackhardasarock.wav
    track: music
    volume: 1.0
  music_jungleboogie:
    file: soundtrack-jungleboogie.wav
    volume: 1.0
  music_wasted:
    file: soundtrack-wasted.wav
    volume: 1.0
  voice_sink2left:
    file: notthatdrunk1.wav
    track: voice
    volume: 1.0
    ducking:
        target: music
        delay: 0
        attack: 0.3 sec
        attenuation: -18db
        release_point: 1.0 sec
        release: 3.0 sec
  voice_sink1left:
    file: notthatdrunk2.wav
    track: voice
    volume: 1.0
    ducking:
        target: music
        delay: 0
        attack: 0.3 sec
        attenuation: -18db
        release_point: 1.0 sec
        release: 3.0 sec
  voice_betterwhendrunk:
    file: betterwhendrunk.wav
    track: voice
    volume: 1.0
    ducking:
        target: music
        delay: 0
        attack: 0.3 sec
        attenuation: -50db
        release_point: .5 sec
        release: 1.5 sec
  voice_longpour_intro:
    file: modeintro-longpour.wav
    track: voice
    volume: 1.0
    ducking:
        target: music
        delay: 0
        attack: 0.3 sec
        attenuation: -50db
        release_point: .5 sec
        release: 1.5 sec
  voice_quarters_intro:
    file: modeintro-quarters.wav
    track: voice
    volume: 1.0
    ducking:
        target: music
        delay: 0
        attack: 0.3 sec
        attenuation: -50db
        release_point: .5 sec
        release: 1.5 sec
  voice_strikeout_intro:
    file: modeintro-strikeout.wav
    track: voice
    volume: 1.0
    ducking:
        target: music
        delay: 0
        attack: 0.3 sec
        attenuation: -50db
        release_point: .5 sec
        release: 1.5 sec
  voice_volumechug_intro:
    file: modeintro-volumechug.wav
    track: voice
    volume: 1.0
    ducking:
        target: music
        delay: 0
        attack: 0.3 sec
        attenuation: -50db
        release_point: .5 sec
        release: 1.5 sec
  voice_trojankeg_intro:
    file: modeintro-trojankeg.wav
    track: voice
    volume: 1.0
    ducking:
        target: music
        delay: 0
        attack: 0.3 sec
        attenuation: -50db
        release_point: .5 sec
        release: 1.5 sec
  voice_dasboot_intro:
    file: modeintro-dasboot.wav
    track: voice
    volume: 1.0
    ducking:
        target: music
        delay: 0
        attack: 0.3 sec
        attenuation: -50db
        release_point: .5 sec
        release: 1.5 sec
  voice_cheers:
    file: cheers.wav
    track: voice
    volume: 1.0
    ducking:
        target: music
        delay: 0
        attack: 0.3 sec
        attenuation: -50db
        release_point: .5 sec
        release: 1.5 sec     
  voice_eyeofjew:
    file: eyeofthejew1.wav
    track: voice
    volume: 1.0
    ducking:
        target: music
        delay: 0
        attack: 0.3 sec
        attenuation: -50db
        release_point: .5 sec
        release: 1.5 sec
  voice_soberasabird:
    file: soberasabird.wav
    track: voice
    volume: 1.0
    ducking:
        target: music
        delay: 0
        attack: 0.3 sec
        attenuation: -50db
        release_point: .5 sec
        release: 1.5 sec

  voice_tavern:
    file: tavern1.wav
    track: voice
    volume: 1.0
    #ducking:
    #    target: music
    #    delay: 0
    #    attack: 0.3 sec
    #    attenuation: -50db
    #    release_point: .5 sec
    #    release: 1.5 sec

  # death clips  
  voice_drain_cantdrinkabeer:
    file: death-cantdrinkabeer.wav
    track: voice
    volume: 1.0
    ducking:
        target: music
        delay: 0
        attack: 0.3 sec
        attenuation: -50db
        release_point: .5 sec
        release: 1.5 sec
  voice_drain_firstbeer:
    file: death-firstbeer.wav
    track: voice
    volume: 1.0
    ducking:
        target: music
        delay: 0
        attack: 0.3 sec
        attenuation: -50db
        release_point: .5 sec
        release: 1.5 sec
  voice_drain_nipple:
    file: death-nipple.wav
    track: voice
    volume: 1.0
    ducking:
        target: music
        delay: 0
        attack: 0.3 sec
        attenuation: -50db
        release_point: .5 sec
        release: 1.5 sec
  voice_gameover:
    file: death-stableboy.wav
    track: voice
    volume: 1.0
    ducking:
        target: music
        delay: 0
        attack: 0.3 sec
        attenuation: -50db
        release_point: .5 sec
        release: 1.5 sec
  voice_ballsave:
    file: death-save-landfillalive.wav
    track: voice
    volume: 1.0
    ducking:
        target: music
        delay: 0
        attack: 0.3 sec
        attenuation: -50db
        release_point: .5 sec
        release: 1.5 sec