#config_version=5
##! mode: mball_lock1

mode:
  restart_on_next_ball: true
  start_events: mode_base_started
  stop_events: multiball_pt_multiball_started

multiball_locks:
  pt_lock1:
    lock_devices: bd_pongcup1
    balls_to_lock: 1
    disable_events: mode_multiball_started
    reset_count_for_current_player_events: multiball_pt_multiball_started


