#config_version=5
##! mode: longpour

mode:
  start_events: start_mode_longpour
  stop_events: stop_mode_longpour, stop_missions, timer_round_timer_longpour_stopped   # end round when timer stops
  events_when_started: mode_type_mission_started
  events_when_stopped: mode_type_mission_stopped
  priority: 300

sound_player:
  mode_longpour_started:
    voice_longpour_intro:
      action: play
      loops: 0
      events_when_stopped: kicker_mode_eject, kicker_rimrules_eject, start_background_music
  start_background_music:
    music_hardasarock:
      action: play
      loops: 0
  mode_longpour_will_stop:
    music_hardasarock:
      action: stop  
  
  # Field, and any of the Game Modes (Quarters, Strike Out, etc.) must implement their own listeners on shot_kicker_mode_hit or shot_kicker_rimrules_hit.
  shot_kicker_mode_hit:
    voice_betterwhendrunk:
      action: play
      events_when_stopped: kicker_mode_eject
  shot_kicker_rimrules_hit:
    rimrules:
      action: play
      events_when_stopped: kicker_rimrules_eject

slides:
  show_longpour_slide:
    widgets:
      - type: text
        text: (score)
        number_grouping: true
        min_digits: 2
        font_size: 250
      - type: text
        text: PLAYER (number)
        y: 10
        x: 10
        font_size: 50
        anchor_x: left
        anchor_y: bottom
      - type: text
        text: BALL (ball)
        y: 10
        x: right-10
        anchor_x: right
        anchor_y: bottom
        font_size: 50
      - type: text
        text: LONGPOUR - HIT THOSE RAMPS!
        font_size: 100
        anchor_y: top
        y: top
        anchor_x: middle
        x: middle
      - type: text
        text: (player|timer_longpour_variable)
        anchor_y: bottom
        y: bottom
        anchor_x: middle
        x: middle
        font_size: 150
        color: red

slide_player:
  kicker_mode_eject: show_longpour_slide
  
shows:
  show_flash_longpour:
    - time: 0
      lights:
        mode_longpour:
          color: red
          fade: .1s
    - time: '+1'
      lights:
        mode_longpour: 
          color: white
          fade: .1s
    - time: '+1'
      lights:
        mode_longpour:
          color: blue
          fade: .1s
  show_init_longpour:
    - time: 0
      lights:
        slingquarters_upper: white
        slingquarters_lower: white
        slingleft_upper: white
        slingleft_lower: white
        slingright_upper: white
        slingright_lower: white
        flipper_left: white
        flipper_right: white
    - duration: -1

show_player:
  mode_longpour_started: show_init_longpour
  kicker_mode_eject:
    show_flash_longpour:
      speed: 4
  kicker_mode_eject.1:
    show_flash_ramps:
      speed: 4
  kicker_mode_eject.2:
    show_flash_gi_back:
      speed: 15
  kicker_mode_eject.3:
    show_flash_gi_sides:
      speed: 6
  kicker_mode_eject.4:
    show_flash_slings:
      speed: 6

# timed round
timers:
  round_timer_longpour:
    start_value: 30
    end_value: 0
    direction: down
    control_events:
      - action: start
        event: kicker_mode_eject

variable_player:
  mode_longpour_started:
    has_longpour:
      action: set
      int: 1
  timer_round_timer_longpour_tick:
    timer_longpour_variable:
      int: device.timers.round_timer_longpour.ticks
      action: set
  shot_diverter_hit:
    score: 100000
  shot_ramp_drinko_hit:
    score: 100000
  shot_tavern_hit:
    score: 100000



