#config_version=5
##! mode: longpour

mode:
  start_events: start_mode_longpour
  stop_events: stop_mode_longpour, stop_missions, timer_round_timer_longpour_stopped   # end round when timer stops
  events_when_started: mode_type_mission_started
  events_when_stopped: mode_type_mission_stopped
  priority: 300

sound_player:
  #mode_longpour_started:
  #  introrepeat:
  #    action: stop
  mode_longpour_started.1:
    voice_longpour_intro:
      action: play
      loops: 0
      events_when_stopped: kicker_mode_eject
  kicker_mode_eject:
    music_hardasarock:
      action: play
      loops: 0
  mode_longpour_will_stop:
    music_hardasarock:
      action: stop
  #mode_longpour_will_stop.1:
  #  introrepeat:
  #    action: play
  #    loops: -1
  shot_diverter_hit:
    2burps:
      action: play
  shot_ramp_drinko_hit:
    2burps:
      action: play
  spinner_tavern_spinner_active:
    voice_tavern:
      action: play
  shot_take_hit_hit:
    takeahit:
      action: play
  shot_chug_beer_hit:
    chugyourbeer:
      action: play
  shot_do_shot_hit:
    doashot:
      action: play
  play_betterwhendrunk_and_eject:
    voice_betterwhendrunk:
      action: play
      events_when_stopped: kicker_mode_eject
  shot_kicker_rimrules_hit:
    rimrules:
      action: play
      events_when_stopped: kicker_rimrules_eject
  shot_trojankeg_left_hit:
    prosit:
      action: play
  shot_trojankeg_middle_hit:
    prosit:
      action: play
  shot_trojankeg_right_hit:
    prosit:
      action: play
  shot_chance_hit:
    chance:
      action: play
  shot_special_hit:
    unddrinken:
      action: play    
  shot_quarters_hit:
    quarters:
      action: play
  shot_pongcup1_hit:
    voice_sink2left:
      action: play
      events_when_stopped: pongtable_movetocup2
  shot_pongcup2_hit:
    voice_sink1left:
      action: play
      events_when_stopped: pongtable_movetocupNone
     

slides:
  show_default:
    widgets:
      - type: text
        text: (score)
        number_grouping: true
        min_digits: 2
        font_size: 250
      - type: text
        text: PLAYER (number)
        y: 10
        x: 10
        font_size: 50
        anchor_x: left
        anchor_y: bottom
      - type: text
        text: BALL (ball)
        y: 10
        x: right-10
        anchor_x: right
        anchor_y: bottom
        font_size: 50
      - type: text
        text: LONGPOUR - HIT THOSE RAMPS!
        font_size: 100
        anchor_y: top
        y: top
        anchor_x: middle
        x: middle
      - type: text
        text: (player|timer_longpour_variable)
        anchor_y: bottom
        y: bottom
        anchor_x: middle
        x: middle
        font_size: 150
        color: red

slide_player:
  kicker_mode_eject: show_default
  
shows:
  flash_longpour_insert:
    - time: 0
      lights:
        mode_longpour:
          color: red
          fade: .1s
    - time: '+1'
      lights:
        mode_longpour: 
          color: white
          fade: .1s
    - time: '+1'
      lights:
        mode_longpour:
          color: blue
          fade: .1s

show_player:
  kicker_mode_eject:
    flash_longpour_insert:
      speed: 4

# timed round
timers:
  round_timer_longpour:
    start_value: 30
    end_value: 0
    direction: down
    control_events:
      - action: start
        event: kicker_mode_eject

variable_player:
  mode_longpour_started:
    has_longpour:
      action: set
      int: 1
  timer_round_timer_longpour_tick:
    timer_longpour_variable:
      int: device.timers.round_timer_longpour.ticks
      action: set
  shot_diverter_hit:
    score: 100000
  shot_ramp_drinko_hit:
    score: 100000
  shot_tavern_spinner_hit:
    score: 50000



