#config_version=5
##! mode: field

mode:
  start_events: start_mode_field
  stop_events: stop_mode_field
  priority: 300

config:
  - mug.yaml
  - qualify.yaml
  - drinko_bonus.yaml

sound_player:
  mode_field_started:
    introrepeat:
      action: play
      track: music
      loops: -1
      volume: .5
  mode_field_will_stop:
    introrepeat:
      action: stop

event_player:
  shot_kicker_mode_hit{device.counters.count_mug_lights.value >= 14}: launch_random_game_mode
  shot_kicker_mode_hit{device.counters.count_mug_lights.value < 14}: play_betterwhendrunk_and_eject
  shot_kicker_rimrules_hit{device.counters.count_mug_lights.value >= 14}: launch_random_game_mode
  shot_kicker_rimrules_hit{device.counters.count_mug_lights.value < 14}: play_rimrules_and_eject

random_event_player:
  launch_random_game_mode:
    events:
      - start_mode_longpour
      - start_mode_quarters
      - start_mode_strikeout
      
show_player:
  mode_field_started:
    qualifying_show:
      speed: 4
