#config_version=5

shows:
  show_qualify_active:
    - duration: 1
      lights:
        strikeout_shot:
          color: red
          fade: .1s
        strikeout_beer:
          color: red
          fade: .1s
        strikeout_bong: 
          color: red
          fade: .1s
        quarters: 
          color: red
          fade: .1s
        trojankeg_left: 
          color: red
          fade: .1s
        trojankeg_middle: 
          color: red
          fade: .1s
        trojankeg_right: 
          color: red
          fade: .1s
        chance: 
          color: red
          fade: .1s
        special: 
          color: red
          fade: .1s
        arrow_tavern1: 
          color: red
          fade: .1s
        arrow_tavern2: 
          color: off
          fade: .1s
        arrow_tavern3: 
          color: off
          fade: .1s
        arrow_boot1: 
          color: red
          fade: .1s
        arrow_boot2: 
          color: off
          fade: .1s
        arrow_boot3: 
          color: off
          fade: .1s
        arrow_drinko1: 
          color: red
          fade: .1s
        arrow_drinko2: 
          color: off
          fade: .1s
        arrow_drinko3: 
          color: off
          fade: .1s
        l_popbumper_left: 
          color: on
          fade: .1s
        l_popbumper_right: 
          color: off
          fade: .1s
        l_popbumper_lower: 
          color: off
          fade: .1s
    - duration: 1
      lights:
        strikeout_shot: 
          color: white
          fade: .1s
        strikeout_beer: 
          color: white
          fade: .1s
        strikeout_bong: 
          color: white
          fade: .1s
        quarters: 
          color: white
          fade: .1s
        trojankeg_left: 
          color: white
          fade: .1s
        trojankeg_middle: 
          color: white
          fade: .1s
        trojankeg_right: 
          color: white
          fade: .1s
        chance: 
          color: white
          fade: .1s
        special: 
          color: white
          fade: .1s
        arrow_tavern1: 
          color: off
          fade: .1s
        arrow_tavern2: 
          color: white
          fade: .1s
        arrow_boot1: 
          color: off
          fade: .1s
        arrow_boot2: 
          color: white
          fade: .1s
        arrow_drinko1: 
          color: off
          fade: .1s
        arrow_drinko2: 
          color: white
          fade: .1s
        l_popbumper_left: 
          color: off
          fade: .1s
        l_popbumper_right: 
          color: on
          fade: .1s
    - duration: 1
      lights:
        strikeout_shot: 
          color: blue
          fade: .1s
        strikeout_beer: 
          color: blue
          fade: .1s
        strikeout_bong: 
          color: blue
          fade: .1s
        quarters: 
          color: blue
          fade: .1s
        trojankeg_left: 
          color: blue
          fade: .1s
        trojankeg_middle: 
          color: blue
          fade: .1s
        trojankeg_right: 
          color: blue
          fade: .1s
        chance: 
          color: blue
          fade: .1s
        special: 
          color: blue
          fade: .1s
        arrow_tavern2: 
          color: off
          fade: .1s
        arrow_tavern3: 
          color: blue
          fade: .1s
        arrow_boot2: 
          color: off
          fade: .1s
        arrow_boot3: 
          color: blue
          fade: .1s
        arrow_drinko2: 
          color: off
          fade: .1s
        arrow_drinko3: 
          color: blue
          fade: .1s
        l_popbumper_right: 
          color: off
          fade: .1s
        l_popbumper_lower: 
          color: on
          fade: .1s
  show_qualified_arrows:
    - duration: 1
      lights:
        arrow_mode1: 
          color: red
          fade: .1s
        arrow_rimrules1: 
          color: red
          fade: .1s
        arrow_mode2: 
          color: off
          fade: .1s
        arrow_rimrules2: 
          color: off
          fade: .1s
        arrow_mode3: 
          color: off
          fade: .1s
        arrow_rimrules3: 
          color: off
          fade: .1s
    - duration: 1
      lights:
        arrow_mode1: 
          color: off
          fade: .1s
        arrow_rimrules1: 
          color: off
          fade: .1s
        arrow_mode2: 
          color: white
          fade: .1s
        arrow_rimrules2: 
          color: white
          fade: .1s
        arrow_mode3: 
          color: off
          fade: .1s
        arrow_rimrules3: 
          color: off
          fade: .1s
    - duration: 1
      lights:
        arrow_mode1: 
          color: off
          fade: .1s
        arrow_rimrules1: 
          color: off
          fade: .1s
        arrow_mode2: 
          color: off
          fade: .1s
        arrow_rimrules2: 
          color: off
          fade: .1s
        arrow_mode3: 
          color: blue
          fade: .1s
        arrow_rimrules3: 
          color: blue
          fade: .1s

show_player:
  qualified_for_mode_selection:
    show_qualified_arrows:
      speed: 4