#config_version=5

shows:
  show_qualify_active:
    - time: 0
      lights:
        strikeout_shot: red
        strikeout_beer: red
        strikeout_bong: red
        quarters: red
        trojankeg_left: red
        trojankeg_middle: red
        trojankeg_right: red
        chance: red
        special: red
    - time: '+1'
      lights:
        strikeout_shot: white
        strikeout_beer: white
        strikeout_bong: white
        quarters: white
        trojankeg_left: white
        trojankeg_middle: white
        trojankeg_right: white
        chance: white
        special: white
    - time: '+1'
      lights:
        strikeout_shot: blue
        strikeout_beer: blue
        strikeout_bong: blue
        quarters: blue
        trojankeg_left: blue
        trojankeg_middle: blue
        trojankeg_right: blue
        chance: blue
        special: blue
  show_qualified_arrows:
    - duration: 1
      lights:
        arrow_mode1: red
        arrow_rimrules1: red
        arrow_mode2: off
        arrow_rimrules2: off
        arrow_mode3: off
        arrow_rimrules3: off
    - duration: 1
      lights:
        arrow_mode1: off
        arrow_rimrules1: off
        arrow_mode2: white
        arrow_rimrules2: white
        arrow_mode3: off
        arrow_rimrules3: off
    - duration: 1
      lights:
        arrow_mode1: off
        arrow_rimrules1: off
        arrow_mode2: off
        arrow_rimrules2: off
        arrow_mode3: blue
        arrow_rimrules3: blue

show_player:
  qualified_for_mode_selection:
    show_qualified_arrows:
      speed: 4