#config_version=5

shows:
  flash_lights:
    - duration: 1
      lights:
        arrow_mode1: red
        arrow_rimrules1: red
        arrow_mode2: off
        arrow_rimrules2: off
        arrow_mode3: off
        arrow_rimrules3: off
    - duration: 1
      lights:
        arrow_mode1: off
        arrow_rimrules1: off
        arrow_mode2: white
        arrow_rimrules2: white
        arrow_mode3: off
        arrow_rimrules3: off
    - duration: 1
      lights:
        arrow_mode1: off
        arrow_rimrules1: off
        arrow_mode2: off
        arrow_rimrules2: off
        arrow_mode3: blue
        arrow_rimrules3: blue

show_player:
  start_qualify:
    flash_lights:
      speed: 4