#config_version=5
##! mode: strikeout

mode:
  start_events: start_mode_strikeout
  stop_events: stop_mode_strikeout, stop_missions, timer_round_timer_strikeout_stopped   # end round when timer stops
  events_when_started: mode_type_mission_started
  events_when_stopped: mode_type_mission_stopped
  priority: 300

sound_player:
  mode_strikeout_started:
    voice_strikeout_intro:
      action: play
      events_when_stopped: kicker_mode_eject

shows:
  flash_strikeout_insert:
    - time: 0
      lights:
        mode_strikeout:
          color: red
          fade: .1s
    - time: '+1'
      lights:
        mode_strikeout: 
          color: white
          fade: .1s
    - time: '+1'
      lights:
        mode_strikeout:
          color: blue
          fade: .1s

show_player:
  kicker_mode_eject:
    flash_strikeout_insert:
      speed: 4

# timed round
timers:
  round_timer_strikeout:
    start_value: 5
    end_value: 0
    direction: down
    control_events:
      - action: start
        event: kicker_mode_eject

variable_player:
  mode_strikeout_started:
    has_strikeout:
      action: set
      int: 1